proxy:
  image: agaveapi/apache-api-proxy
  command:
  hostname: docker.example.com
  ports:
    - "443:443"
    - "80:80"
  links:
    - lb
    - mysql
    - mongo
    - beanstalk
lb:
  image: 'ehazlett/interlock:latest'
  command: '--swarm-url "tcp://192.168.59.103:2375" --plugin haproxy start'
  hostname: docker.example.com
  environment:
  ports:
    - '8080:8080'
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
mysql:
  image: deardooley/mysql
  hostname: docker.example.com
  ports:
    - '3306:3306'
  restart: always
  environment:
    - 'MYSQL_DATABASE=agave'
    - 'MYSQL_USER=agaveuser'
    - 'MYSQL_PASSWORD=password'
    - 'MYSQL_ROOT_PASSWORD=mysecretpassword'
    - 'INTERLOCK_DATA=''{"alias_domains": ["mysql"], "port": 3306}'''
  volumes:
    - /home/rodeo/cache/mysql:/var/lib/mysql
mongo:
  image: mongo:2.6
  command: --smallfiles
  hostname: docker.example.com
  ports:
    - '27017:27017'
  restart: always
  volumes:
    - /home/rodeo/cache/mongo:/data/db
beanstalk:
  image: agaveapi/beanstalkd
  hostname: docker.example.com
  ports:
    - '11300:11300'
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["beanstalk","queue"], "port": 11300, "warm": false}'''
jobs:
  image: agaveapi/jobs-api:2.1.2
  hostname: docker.example.com
  ports:
    - "8080"
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["jobs"], "port": 8080, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'
    - 'MYSQL_DATABASE=agave'
    - 'FOUNDATION_SERVICE_LOG=logging'
    - 'FOUNDATION_SERVICE_MESSAGING_HOST=beanstalk'
    - 'FOUNDATION_SERVICE_MESSAGING_PORT=11300'
    - 'FOUNDATION_SERVICE_SLAVE_MODE=false'
    - 'FOUNDATION_SERVICE_STAGING_MAX_TASKS=0'
    - 'FOUNDATION_SERVICE_ARCHIVING_MAX_TASKS=0'
    - 'FOUNDATION_SERVICE_JOBS_MAX_TASKS=0'
    - 'FOUNDATION_SERVICE_MONITORING_MAX_TASKS=0'
    - 'MAIL_SMTPS_HOST=smtp.sendgrid.net'
    - 'MAIL_SMTPS_PORT=587'
    - 'MAIL_SMTPS_USER=agaveapi'
    - 'MAIL_SMTPS_PWD=W^1JLNJVFGy8'
    - 'MAIL_SMTPS_FROM_NAME="Agave Dev Notification Service"'
    - 'MAIL_SMTPS_FROM_ADDRESS="dev-no-reply@example.com"'
    - 'IPLANT_DEDICATED_TENANT_ID='
    - 'IPLANT_DRAIN_ALL_QUEUES=false'
jobsworker:
  image: agaveapi/jobs-api:2.1.2
  hostname: docker.example.com
  ports:
    - "8080"
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["jobsworker"], "port": 8080, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'
    - 'MYSQL_DATABASE=agave'
    - 'FOUNDATION_SERVICE_LOG=logging'
    - 'FOUNDATION_SERVICE_MESSAGING_HOST=beanstalk'
    - 'FOUNDATION_SERVICE_MESSAGING_PORT=11300'
    - 'FOUNDATION_SERVICE_SLAVE_MODE=true'
    - 'FOUNDATION_SERVICE_STAGING_MAX_TASKS=2'
    - 'FOUNDATION_SERVICE_ARCHIVING_MAX_TASKS=2'
    - 'FOUNDATION_SERVICE_JOBS_MAX_TASKS=2'
    - 'FOUNDATION_SERVICE_MONITORING_MAX_TASKS=1'
    - 'IPLANT_DEDICATED_TENANT_ID='
    - 'IPLANT_DRAIN_ALL_QUEUES=false'
    - 'MAIL_SMTPS_HOST=smtp.sendgrid.net'
    - 'MAIL_SMTPS_PORT=587'
    - 'MAIL_SMTPS_USER=agaveapi'
    - 'MAIL_SMTPS_PWD=W^1JLNJVFGy8'
    - 'MAIL_SMTPS_FROM_NAME="Agave Dev Notification Service"'
    - 'MAIL_SMTPS_FROM_ADDRESS="dev-no-reply@example.com"'
notifications:
  image: agaveapi/notifications-api:2.1.2
  hostname: docker.example.com
  ports:
    - "8080"
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["notifications"], "port": 8080, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'
    - 'MYSQL_DATABASE=agave'
    - 'FOUNDATION_SERVICE_LOG=logging'
    - 'FOUNDATION_SERVICE_MESSAGING_HOST=beanstalk'
    - 'FOUNDATION_SERVICE_MESSAGING_PORT=11300'
    - 'FOUNDATION_SERVICE_SLAVE_MODE=false'
    - 'IPLANT_MAX_NOTIFICATION_TASKS=0'
    - 'MAIL_SMTPS_HOST=smtp.sendgrid.net'
    - 'MAIL_SMTPS_PORT=587'
    - 'MAIL_SMTPS_USER=agaveapi'
    - 'MAIL_SMTPS_PWD=W^1JLNJVFGy8'
    - 'MAIL_SMTPS_FROM_NAME="Agave Dev Notification Service"'
    - 'MAIL_SMTPS_FROM_ADDRESS="dev-no-reply@example.com"'
    - 'IPLANT_DEDICATED_TENANT_ID='
    - 'IPLANT_DRAIN_ALL_QUEUES=false'
notificationsworker:
  image: agaveapi/notifications-api:2.1.2
  hostname: docker.example.com
  ports:
    - "8080"
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["notificationsworker"], "port": 8080, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'
    - 'MYSQL_DATABASE=agave'
    - 'FOUNDATION_SERVICE_LOG=logging'
    - 'FOUNDATION_SERVICE_MESSAGING_HOST=beanstalk'
    - 'FOUNDATION_SERVICE_MESSAGING_PORT=11300'
    - 'FOUNDATION_SERVICE_SLAVE_MODE=true'
    - 'IPLANT_MAX_NOTIFICATION_TASKS=1'
    - 'MAIL_SMTPS_HOST=smtp.sendgrid.net'
    - 'MAIL_SMTPS_PORT=587'
    - 'MAIL_SMTPS_USER=agaveapi'
    - 'MAIL_SMTPS_PWD=W^1JLNJVFGy8'
    - 'MAIL_SMTPS_FROM_NAME="Agave Dev Notification Service"'
    - 'MAIL_SMTPS_FROM_ADDRESS="dev-no-reply@example.com"'
    - 'IPLANT_DEDICATED_TENANT_ID='
    - 'IPLANT_DRAIN_ALL_QUEUES=false'
logging:
  image: agaveapi/logging-api:2.1.2
  hostname: docker.example.com
  ports:
    - "80"
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["logging"], "port": 80, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'
    - 'MYSQL_DATABASE=agave'
