lb:
  image: 'ehazlett/interlock:latest'
  command: '--plugin haproxy start'
  environment:
    - 'HAPROXY_PROXY_BACKEND_OVERRIDE_ADDRESS=tcp://0.0.0.0:2375'
  ports:
    - '80:8080'
  restart: always
  tags:
    - core
    - development

mysql:
  image: deardooley/mysql
  ports:
    - '3306:3306'
  restart: always
  environment:
    - 'MYSQL_DATABASE=agave'
    - 'MYSQL_USER=agaveuser'
    - 'MYSQL_PASSWORD=password'
    - 'MYSQL_ROOT_PASSWORD=mysecretpassword'
    - 'INTERLOCK_DATA=''{"alias_domains": ["mysql"], "port": 3306, "warm": false}'''
  volumes:
    - /home/rodeo/cache/mysql:/var/lib/mysql
  tags:
    - core
    - development

mongo:
  image: mongo:2.6
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["nosql","mongo"], "port": 27017, "warm": false}'''
  restart: always
  volumes:
    - /home/rodeo/cache/mongo:/data/db

beanstalk:
  image: agaveapi/beanstalkd
  ports:
    - '11300:11300'
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["beanstalk","queue"], "port": 11300, "warm": false}'''
  tags:
    - core
    - development

jobs:
  image: deardooley/agaveapi/jobs-api:latest
  ports:
    - "8080"
  tags:
    - core
    - development
    - api
  autoredeploy: true
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["jobs"], "port": 8080, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'  
    - 'MYSQL_DATABASE=agave'
    - 'FOUNDATION_SERVICE_LOG=logging'
    - 'FOUNDATION_SERVICE_MESSAGING_HOST=beanstalk'
    - 'FOUNDATION_SERVICE_MESSAGING_PORT=11300'
    - 'FOUNDATION_SERVICE_SLAVE_MODE=false'

    - 'FOUNDATION_SERVICE_STAGING_MAX_TASKS=0'
    - 'FOUNDATION_SERVICE_ARCHIVING_MAX_TASKS=0'
    - 'FOUNDATION_SERVICE_JOBS_MAX_TASKS=0'
    - 'FOUNDATION_SERVICE_MONITORING_MAX_TASKS=0'

    - 'MAIL_SMTPS_HOST=smtp.sendgrid.net'
    - 'MAIL_SMTPS_PORT=587'
    - 'MAIL_SMTPS_USER=agaveapi'
    - 'MAIL_SMTPS_PWD=W^1JLNJVFGy8'
    - 'MAIL_SMTPS_FROM_NAME="Agave Dev Notification Service"'
    - 'MAIL_SMTPS_FROM_ADDRESS="dev-no-reply@example.com"' 

    - 'IPLANT_DEDICATED_TENANT_ID='
    - 'IPLANT_DRAIN_ALL_QUEUES=false'
    
jobs-worker:
  image: deardooley/agaveapi/jobs-api:latest
  ports:
    - "8080"
  tags:
    - core
    - development
    - worker
  autoredeploy: true
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["jobs-worker"], "port": 8080, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'  
    - 'MYSQL_DATABASE=agave'
    - 'FOUNDATION_SERVICE_LOG=logging'
    - 'FOUNDATION_SERVICE_MESSAGING_HOST=beanstalk'
    - 'FOUNDATION_SERVICE_MESSAGING_PORT=11300'
    - 'FOUNDATION_SERVICE_SLAVE_MODE=true'

    - 'FOUNDATION_SERVICE_STAGING_MAX_TASKS=2'
    - 'FOUNDATION_SERVICE_ARCHIVING_MAX_TASKS=2'
    - 'FOUNDATION_SERVICE_JOBS_MAX_TASKS=2'
    - 'FOUNDATION_SERVICE_MONITORING_MAX_TASKS=1'

    - 'IPLANT_DEDICATED_TENANT_ID='
    - 'IPLANT_DRAIN_ALL_QUEUES=false'

    - 'MAIL_SMTPS_HOST=smtp.sendgrid.net'
    - 'MAIL_SMTPS_PORT=587'
    - 'MAIL_SMTPS_USER=agaveapi'
    - 'MAIL_SMTPS_PWD=W^1JLNJVFGy8'
    - 'MAIL_SMTPS_FROM_NAME="Agave Dev Notification Service"'
    - 'MAIL_SMTPS_FROM_ADDRESS="dev-no-reply@example.com"' 


notifications:
  image: deardooley/agaveapi/notifications-api:latest
  ports:
    - "8080"
  tags:
    - core
    - development
    - api
  autoredeploy: true
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["notifications"], "port": 8080, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'  
    - 'MYSQL_DATABASE=agave'
    - 'FOUNDATION_SERVICE_LOG=logging'
    - 'FOUNDATION_SERVICE_MESSAGING_HOST=beanstalk'
    - 'FOUNDATION_SERVICE_MESSAGING_PORT=11300'
    - 'FOUNDATION_SERVICE_SLAVE_MODE=false'
    - 'IPLANT_MAX_NOTIFICATION_TASKS=0'

    - 'MAIL_SMTPS_HOST=smtp.sendgrid.net'
    - 'MAIL_SMTPS_PORT=587'
    - 'MAIL_SMTPS_USER=agaveapi'
    - 'MAIL_SMTPS_PWD=W^1JLNJVFGy8'
    - 'MAIL_SMTPS_FROM_NAME="Agave Dev Notification Service"'
    - 'MAIL_SMTPS_FROM_ADDRESS="dev-no-reply@example.com"'    

    - 'IPLANT_DEDICATED_TENANT_ID='
    - 'IPLANT_DRAIN_ALL_QUEUES=false'

notifications-worker:
  image: deardooley/agaveapi/notifications-api:latest
  ports:
    - "8080"
  tags:
    - core
    - development
    - worker
  autoredeploy: true
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["notifications-worker"], "port": 8080, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'  
    - 'MYSQL_DATABASE=agave'
    - 'FOUNDATION_SERVICE_LOG=logging'
    - 'FOUNDATION_SERVICE_MESSAGING_HOST=beanstalk'
    - 'FOUNDATION_SERVICE_MESSAGING_PORT=11300'
    - 'FOUNDATION_SERVICE_SLAVE_MODE=true'

    - 'IPLANT_MAX_NOTIFICATION_TASKS=1'

    - 'MAIL_SMTPS_HOST=smtp.sendgrid.net'
    - 'MAIL_SMTPS_PORT=587'
    - 'MAIL_SMTPS_USER=agaveapi'
    - 'MAIL_SMTPS_PWD=W^1JLNJVFGy8'
    - 'MAIL_SMTPS_FROM_NAME="Agave Dev Notification Service"'
    - 'MAIL_SMTPS_FROM_ADDRESS="dev-no-reply@example.com"'    

    - 'IPLANT_DEDICATED_TENANT_ID='
    - 'IPLANT_DRAIN_ALL_QUEUES=false'
    
logging:
  image: deardooley/agaveapi/logging-api:latest
  ports:
    - "80"
  tags:
    - core
    - development
    - api
  autoredeploy: true
  restart: always
  environment:
    - 'INTERLOCK_DATA=''{"alias_domains": ["logging"], "port": 80, "warm": true}'''
    - 'MYSQL_HOST=db.dev.agaveapi.co'
    - 'MYSQL_PORT=3306'
    - 'MYSQL_USERNAME=agave'
    - 'MYSQL_PASSWORD=password'  
    - 'MYSQL_DATABASE=agave'